image: node:14.16.0

stages:
  - check
  - test
  - release
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/

check-coverage-configuration:
  stage: check
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-check/
  script:
    - git fetch origin master
    - yarn run check_coverage_config

test_mr:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
  script:
    - yarn
    - yarn run lint
    - yarn run jest

release-patch:
  stage: release
  when: manual
  only:
    - master
  after_script:
    - git push repo HEAD:master --tags
  script:
    - npm version patch -m "Release %s"
  before_script:
    - git config --global user.email "bang@eoh.io"
    - git config --global user.name "Bang Dao"
    - git remote add repo https://react-native-smart-city:$PROJECT_ACCESS_TOKEN@gitlab.com/eohio/react-native-smart-city.git || echo "Good"

release-minor:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version minor -m "Release %s"

release-major:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version major -m "Release %s"

publish-npm:
  stage: publish
  only:
    - /\d+\.\d+\.\d+/
  script:
    - git fetch origin master
    - apt list openssh-client -a
    - eval $(ssh-agent -s)
    - chmod 600 $GITHUB_DEPLOY_KEY
    - ssh-add $GITHUB_DEPLOY_KEY
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
    - git remote add github git@github.com:eohjsc/react-native-smart-city.git || echo "Good"
    - ssh -o StrictHostKeyChecking=no git@github.com || echo "Good"
    - git push -f github origin/master:master
    - npm publish
